package me.prexorjustin.prexorcloud.controller.template;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import me.prexorjustin.prexorcloud.controller.event.EventBus;
import me.prexorjustin.prexorcloud.controller.state.StateStore;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
@DisplayName("BaseTemplateGenerator")
class BaseTemplateGeneratorTest {

    @TempDir
    Path tempDir;

    @Mock
    StateStore stateStore;

    private TemplateManager templateManager;
    private BaseTemplateGenerator generator;

    @BeforeEach
    void setUp() {
        templateManager = new TemplateManager(tempDir, stateStore, new EventBus());
        generator = new BaseTemplateGenerator(templateManager);
    }

    @Test
    @DisplayName("installs the Geyser integration as an Extension (extensions/, not plugins/) with default config")
    void geyserTemplateInstallsExtensionInExtensionsDir() throws Exception {
        generator.ensureBaseTemplates();
        generator.ensurePlatformTemplate("GEYSER", "PROXY", "geyser");

        Path filesDir = templateManager.getTemplateFilesDir("base-geyser");
        assertTrue(
                Files.exists(filesDir.resolve("extensions/PrexorCloudGeyserExtension.jar")),
                "Geyser jar must be installed under extensions/");
        assertFalse(
                Files.exists(filesDir.resolve("plugins/PrexorCloudGeyserExtension.jar")),
                "Geyser jar must NOT be installed under plugins/");
        assertTrue(Files.exists(filesDir.resolve("config.yml")), "default geyser config.yml must be shipped");
    }

    @Test
    @DisplayName("refreshBundledPlugins replaces a stale bundled jar in an existing template with the classpath copy")
    void refreshReplacesStaleBundledJar() throws Exception {
        generator.ensureBaseTemplates();
        generator.ensurePlatformTemplate("GEYSER", "PROXY", "geyser");

        Path jar = templateManager.getTemplateFilesDir("base-geyser").resolve("extensions/PrexorCloudGeyserExtension.jar");
        byte[] shipped = Files.readAllBytes(jar);

        // Simulate a template generated by an older controller: overwrite with stale bytes.
        Files.write(jar, "STALE-OLD-PLUGIN".getBytes(StandardCharsets.UTF_8));

        generator.refreshBundledPlugins();

        assertArrayEquals(shipped, Files.readAllBytes(jar), "stale bundled jar must be refreshed to the classpath copy");
    }

    @Test
    @DisplayName("refreshBundledPlugins leaves an up-to-date jar untouched (no spurious rewrite)")
    void refreshLeavesCurrentJarUntouched() throws Exception {
        generator.ensureBaseTemplates();
        generator.ensurePlatformTemplate("GEYSER", "PROXY", "geyser");

        Path jar = templateManager.getTemplateFilesDir("base-geyser").resolve("extensions/PrexorCloudGeyserExtension.jar");
        byte[] before = Files.readAllBytes(jar);

        generator.refreshBundledPlugins();

        assertArrayEquals(before, Files.readAllBytes(jar), "an already-current jar must be left as-is");
    }
}
