package setup

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

// NativeDashboardConfig parameterises a host (non-compose) dashboard install:
// the extracted static bundle is served by a host web server that reverse-
// proxies /api/* to the controller.
type NativeDashboardConfig struct {
	InstallDir    string    // e.g. /opt/prexorcloud/dashboard (web root is <dir>/public)
	PublicURL     string    // operator-visible URL — drives Caddy's auto-HTTPS site address
	ListenPort    string    // host port the web server binds (nginx only; Caddy derives from publicURL)
	ControllerURL string    // controller REST base, proxied at /api/*
	WebServer     WebServer // nginx | caddy
}

// DashboardWebRoot is the directory the static bundle is extracted into and
// the web server serves from.
func DashboardWebRoot(installDir string) string {
	return filepath.Join(installDir, "public")
}

// ExtractDashboardBundle unpacks a dashboard static tarball (produced by
// `tar -C .output/public -czf … .` in release-jars.yml, so entries are rooted
// at "./") into webRoot. Unlike extractTarGz it does not strip a wrapping
// directory — the bundle is already flat. Existing contents are cleared first
// so re-runs don't leave stale hashed assets behind.
func ExtractDashboardBundle(tarPath, webRoot string) error {
	if err := os.RemoveAll(webRoot); err != nil {
		return fmt.Errorf("clear web root %s: %w", webRoot, err)
	}
	if err := os.MkdirAll(webRoot, 0755); err != nil {
		return fmt.Errorf("create web root %s: %w", webRoot, err)
	}

	f, err := os.Open(tarPath)
	if err != nil {
		return err
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		return err
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return err
		}
		rel := strings.TrimPrefix(hdr.Name, "./")
		if rel == "" || rel == "." {
			continue
		}
		// Guard against path traversal in a tarball entry.
		target := filepath.Join(webRoot, rel)
		if !strings.HasPrefix(target, filepath.Clean(webRoot)+string(os.PathSeparator)) {
			return fmt.Errorf("refusing to extract %q outside web root", hdr.Name)
		}
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
				return err
			}
			out, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, os.FileMode(hdr.Mode))
			if err != nil {
				return err
			}
			if _, err := io.Copy(out, tr); err != nil { //nolint:gosec — bundle is cosign+sha256 verified before extraction
				out.Close()
				return err
			}
			out.Close()
		}
	}
	return nil
}

// ConfigureDashboardWebServer writes the chosen web server's vhost config for
// the dashboard and reloads it. The web server package must already be
// installed (InstallNginx / InstallCaddy) and started.
func ConfigureDashboardWebServer(cfg NativeDashboardConfig) error {
	controllerHost, controllerScheme := parseControllerForProxy(cfg.ControllerURL)
	if controllerHost == "" {
		return fmt.Errorf("controller URL %q is not a valid http(s) URL", cfg.ControllerURL)
	}
	controllerOrigin := controllerScheme + "://" + controllerHost
	webRoot := DashboardWebRoot(cfg.InstallDir)

	switch cfg.WebServer {
	case WebServerCaddy:
		return configureCaddy(cfg, webRoot, controllerOrigin)
	case WebServerNginx, "":
		return configureNginx(cfg, webRoot, controllerOrigin)
	default:
		return fmt.Errorf("unsupported web server %q (use nginx or caddy)", cfg.WebServer)
	}
}

func configureNginx(cfg NativeDashboardConfig, webRoot, controllerOrigin string) error {
	conf := fmt.Sprintf(`# Generated by prexorctl (native dashboard install).
# Serves the dashboard SPA and proxies /api/* to %[2]s. TLS is assumed to be
# terminated upstream — front this with a TLS-terminating load balancer, or use
# the Caddy web server for automatic HTTPS.
server {
    listen %[1]s;
    server_name _;
    root %[3]s;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass %[2]s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/events/stream {
        proxy_pass %[2]s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }

    location /metrics {
        proxy_pass %[2]s;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
`, cfg.ListenPort, controllerOrigin, webRoot)

	confPath := "/etc/nginx/conf.d/prexorcloud-dashboard.conf"
	if err := os.WriteFile(confPath, []byte(conf), 0644); err != nil {
		return fmt.Errorf("write %s: %w", confPath, err)
	}
	return reloadOrRestart(nginxServiceName)
}

func configureCaddy(cfg NativeDashboardConfig, webRoot, controllerOrigin string) error {
	site := caddySiteAddress(cfg.PublicURL, cfg.ListenPort)

	conf := fmt.Sprintf(`# Generated by prexorctl (native dashboard install).
# Caddy auto-provisions a Let's Encrypt certificate when the site address is an
# https:// hostname; an http:// address or :port serves plain HTTP.
%[1]s {
	root * %[2]s
	encode gzip

	@api path /api/* /metrics
	handle @api {
		reverse_proxy %[3]s
	}

	handle {
		try_files {path} /index.html
		file_server
	}
}
`, site, webRoot, controllerOrigin)

	confPath := "/etc/caddy/Caddyfile"
	if err := os.MkdirAll(filepath.Dir(confPath), 0755); err != nil {
		return fmt.Errorf("create caddy config dir: %w", err)
	}
	if err := os.WriteFile(confPath, []byte(conf), 0644); err != nil {
		return fmt.Errorf("write %s: %w", confPath, err)
	}
	return reloadOrRestart(caddyServiceName)
}

// caddySiteAddress derives the Caddyfile site address from the public URL.
// https://host → "host" (Caddy auto-HTTPS). http://host → "http://host"
// (plain HTTP, no cert). A bare host or IP falls back to ":listenPort".
func caddySiteAddress(publicURL, listenPort string) string {
	u, err := url.Parse(strings.TrimSpace(publicURL))
	if err != nil || u.Host == "" {
		if listenPort == "" {
			listenPort = "80"
		}
		return ":" + listenPort
	}
	host := u.Hostname()
	if u.Scheme == "https" {
		return host
	}
	return "http://" + host
}
