package setup

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

// DashboardConfig holds the values collected by the dashboard setup wizard.
type DashboardConfig struct {
	InstallDir    string
	PublicURL     string // operator-visible URL (e.g. https://dash.example.com)
	ListenPort    string // host port the nginx container binds (e.g. 80 / 443 / 3000)
	ControllerURL string // base URL of the controller's REST API (e.g. https://controller.example.com:8080)
	TLSMode       string // none | letsencrypt | custom | terminated-upstream
}

// CreateDashboardDirs creates the install directory layout the dashboard
// installer expects.
func CreateDashboardDirs(installDir string) error {
	for _, sub := range []string{"", "config"} {
		if err := os.MkdirAll(filepath.Join(installDir, sub), 0755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Join(installDir, sub), err)
		}
	}
	return nil
}

// WriteDashboardComposeProject emits a docker-compose.yml and a templated
// nginx.conf that runs the published dashboard image, proxies /api/* to the
// configured controller, and listens on the configured host port.
func WriteDashboardComposeProject(installDir string, cfg DashboardConfig) error {
	controllerHost, controllerProto := parseControllerForProxy(cfg.ControllerURL)
	if controllerHost == "" {
		return fmt.Errorf("controller URL %q is not a valid http(s) URL", cfg.ControllerURL)
	}

	nginxConf := dashboardNginxTemplate(cfg.ListenPort, controllerProto+"://"+controllerHost)
	if err := os.WriteFile(filepath.Join(installDir, "nginx.conf"), []byte(nginxConf), 0644); err != nil {
		return fmt.Errorf("write nginx.conf: %w", err)
	}

	compose := fmt.Sprintf(`# Generated by `+"`"+`prexorctl setup --component=dashboard`+"`"+`.
# Bumps the published dashboard image and proxies /api/* to %s.
services:
  dashboard:
    image: ghcr.io/prexorjustin/prexorcloud-dashboard:latest
    restart: unless-stopped
    ports:
      - "%s:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      CONTROLLER_URL: %s
      PUBLIC_URL: %s
`, controllerProto+"://"+controllerHost, cfg.ListenPort, cfg.ControllerURL, cfg.PublicURL)

	if err := os.WriteFile(filepath.Join(installDir, "docker-compose.yml"), []byte(compose), 0644); err != nil {
		return fmt.Errorf("write docker-compose.yml: %w", err)
	}
	return nil
}

// parseControllerForProxy splits the controller URL into the host:port and
// scheme the generated nginx proxy_pass needs. Returns ("", "") on malformed
// input so the caller can surface a clear error.
func parseControllerForProxy(controllerURL string) (hostPort, scheme string) {
	u, err := url.Parse(strings.TrimSpace(controllerURL))
	if err != nil || u.Host == "" {
		return "", ""
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return "", ""
	}
	return u.Host, u.Scheme
}

func dashboardNginxTemplate(listenPort, controllerOrigin string) string {
	// Mirrors dashboard/nginx.conf but with an external controller URL templated
	// in instead of the in-compose "controller" service name. Listens on :3000
	// inside the container; the compose port mapping exposes it on listenPort.
	return fmt.Sprintf(`server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass %[1]s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/v1/events/stream {
        proxy_pass %[1]s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }

    location /metrics {
        proxy_pass %[1]s;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
`, controllerOrigin)
}
