// Velocity-side proxy plugin for the example-playtime module.
//
// Velocity API is stable across 3.x, so no @ForVersion dispatch is needed —
// the plugin class is a single implementation. The CloudPluginProcessor
// generates the Velocity bridge (@Plugin-annotated) and velocity-plugin.json.
plugins {
    id("prexorcloud.plugin-velocity")
}

// The velocity-api jar also ships its own annotation processor, which looks
// for {@code @Plugin}-annotated classes in the source round. Our source only
// declares a {@code CloudPluginBase} subclass; the actual {@code @Plugin}
// class is generated by {@code CloudPluginProcessor} in a later round. That
// mismatch surfaces as "Unable to generate plugin file" during round 1.
//
// The CloudPluginProcessor already writes a complete velocity-plugin.json, so
// velocity's own annotation processor is redundant for cloud-api modules.
// Exclude it to keep compilation one-pass.
configurations.named("annotationProcessor") {
    exclude(group = "com.velocitypowered", module = "velocity-api")
}
