// Copies docs/openapi.json (auto-generated by the controller's
// javalin-openapi-plugin annotation processor) into
// website/public/openapi.json so the Scalar /playground page and any other
// runtime consumer can fetch it as a static asset. starlight-openapi reads
// the source spec directly from docs/openapi.json; the public copy is only
// for runtime consumers.
//
// Runs as `predev` and `prebuild` from package.json. The spec itself is
// produced by `./gradlew :cloud-controller:syncOpenApi` (a finalizedBy on
// compileJava), so any committed copy reflects the latest controller build.
import { copyFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, '../../docs/openapi.json');
const dst = resolve(here, '../public/openapi.json');

if (!existsSync(src)) {
  console.error(`[sync-openapi] source missing: ${src}`);
  console.error(`[sync-openapi] run \`./gradlew :cloud-controller:syncOpenApi\` from java/ to publish the generated spec.`);
  process.exit(1);
}
mkdirSync(dirname(dst), { recursive: true });
copyFileSync(src, dst);
console.log(`[sync-openapi] ${src} -> ${dst}`);
