name: PrexorCloud
version: 1.0.0
main: me.prexorjustin.prexorcloud.server.folia.PrexorCloudFolia
api-version: "1.20"
description: PrexorCloud Folia server integration
authors: [PrexorJustin]
load: STARTUP
folia-supported: true
