import { describe, expect, it, beforeEach, afterEach, vi } from 'vitest';
import { createPinia, setActivePinia } from 'pinia';
import { useWizardStore } from '@/stores/wizard';
import {
  controllerYaml,
  daemonYaml,
  dashboardCompose,
  dashboardNginx,
  dashboardNginxNative,
  dashboardCaddyfile,
  filesForMode,
  modeLabel,
  yamlFor,
} from './yaml';

beforeEach(() => {
  setActivePinia(createPinia());
  // Freeze time so the `# Generated by … · <ISO>` header is stable across runs;
  // the legacy wizard uses the same nowIso() format so we just need any fixed
  // anchor to assert against.
  vi.useFakeTimers();
  vi.setSystemTime(new Date('2026-05-18T12:00:00Z'));
});

afterEach(() => {
  vi.useRealTimers();
});

describe('filesForMode', () => {
  it('emits the right tab set per install mode', () => {
    expect(filesForMode('all')).toEqual(['controller.yml', 'daemon.yml']);
    expect(filesForMode('controller')).toEqual(['controller.yml']);
    expect(filesForMode('daemon')).toEqual(['daemon.yml']);
    expect(filesForMode('dashboard')).toEqual(['docker-compose.yml', 'nginx.conf']);
    expect(filesForMode('cli')).toEqual([]);
  });

  it('native dashboard emits the chosen web server config instead of compose', () => {
    expect(filesForMode('dashboard', 'native', 'caddy')).toEqual(['Caddyfile']);
    expect(filesForMode('dashboard', 'native', 'nginx')).toEqual(['nginx.conf']);
    // Controller/daemon native still produce the same config files as compose.
    expect(filesForMode('all', 'native')).toEqual(['controller.yml', 'daemon.yml']);
  });
});

describe('native dashboard emitters', () => {
  it('dashboardNginxNative listens on the host port and serves the web root', () => {
    const wiz = useWizardStore();
    wiz.dashboardListenPort = 8088;
    wiz.dashboardInstallDir = '/opt/prexorcloud/dashboard';
    wiz.dashboardControllerUrl = 'https://controller.example.com:8080';
    const conf = dashboardNginxNative(wiz.$state);
    expect(conf).toContain('listen 8088;');
    expect(conf).toContain('root /opt/prexorcloud/dashboard/public;');
    expect(conf).toContain('proxy_pass https://controller.example.com:8080;');
  });

  it('dashboardCaddyfile uses a bare host (auto-HTTPS) for an https public URL', () => {
    const wiz = useWizardStore();
    wiz.dashboardPublicUrl = 'https://dash.example.com';
    wiz.dashboardControllerUrl = 'http://10.0.0.5:8080';
    const conf = dashboardCaddyfile(wiz.$state);
    expect(conf).toContain('dash.example.com {');
    expect(conf).not.toContain('https://dash.example.com {');
    expect(conf).toContain('reverse_proxy http://10.0.0.5:8080');
  });

  it('dashboardCaddyfile falls back to http:// for a plain-HTTP public URL', () => {
    const wiz = useWizardStore();
    wiz.dashboardPublicUrl = 'http://dash.local';
    const conf = dashboardCaddyfile(wiz.$state);
    expect(conf).toContain('http://dash.local {');
  });

  it('yamlFor routes nginx.conf to the native vhost when installMode is native', () => {
    const wiz = useWizardStore();
    wiz.setInstallMode('compose');
    expect(yamlFor(wiz.$state, 'nginx.conf')).toContain('listen 3000;');
    // nativeAllowed is false in tests, so set it directly to flip the path.
    wiz.installMode = 'native';
    wiz.dashboardListenPort = 80;
    expect(yamlFor(wiz.$state, 'nginx.conf')).toContain('listen 80;');
  });
});

describe('modeLabel', () => {
  it('renders human labels used in the YAML headers', () => {
    expect(modeLabel('all')).toBe('Controller + Daemon (all-in-one)');
    expect(modeLabel('controller')).toBe('Controller only');
    expect(modeLabel('daemon')).toBe('Daemon only');
    expect(modeLabel('dashboard')).toBe('Dashboard standalone');
  });
});

describe('controllerYaml', () => {
  it('emits the schema header + uuid + http/grpc/database', () => {
    const wiz = useWizardStore();
    wiz.uuid = 'fixed-uuid-for-test';
    const out = controllerYaml(wiz.$state);
    expect(out).toContain('# Generated by PrexorCloud Installer · 2026-05-18T12:00:00Z');
    expect(out).toContain('# Mode: Controller + Daemon (all-in-one)');
    expect(out).toContain('uuid: fixed-uuid-for-test');
    expect(out).toMatch(/http:\n {2}host: 0\.0\.0\.0\n {2}port: 8080/);
    expect(out).toMatch(/grpc:\n {2}host: 0\.0\.0\.0\n {2}port: 9090/);
    expect(out).toContain('database:');
    // URI contains colons → q() wraps it in single quotes.
    expect(out).toContain("  uri: 'mongodb://mongo:27017'");
  });

  it("omits the redis: block in development when redisUri is empty", () => {
    const wiz = useWizardStore();
    wiz.profile = 'development';
    wiz.redisUri = '';
    expect(controllerYaml(wiz.$state)).not.toContain('redis:');
  });

  it('emits the redis: block in production even with empty redisUri', () => {
    const wiz = useWizardStore();
    wiz.profile = 'production';
    wiz.redisUri = '';
    expect(controllerYaml(wiz.$state)).toContain('redis:');
  });

  it('emits passwordReset.smtp.* only when passwordResetEnabled is true', () => {
    const wiz = useWizardStore();
    wiz.passwordResetEnabled = false;
    expect(controllerYaml(wiz.$state)).not.toContain('passwordReset:');
    wiz.passwordResetEnabled = true;
    wiz.smtpHost = 'smtp.example.com';
    const out = controllerYaml(wiz.$state);
    expect(out).toContain('passwordReset:');
    expect(out).toContain('host: smtp.example.com');
  });

  it('derives modules.signing.required from profile when left null', () => {
    const wiz = useWizardStore();
    wiz.modulesSigningRequired = null;
    wiz.profile = 'development';
    expect(controllerYaml(wiz.$state)).toContain('required: false');
    wiz.profile = 'production';
    expect(controllerYaml(wiz.$state)).toContain('required: true');
  });

  it('uses the explicit signing flag when set, overriding profile', () => {
    const wiz = useWizardStore();
    wiz.modulesSigningRequired = true;
    wiz.profile = 'development';
    expect(controllerYaml(wiz.$state)).toContain('required: true');
  });

  it('emits maintenance + share blocks only when enabled', () => {
    const wiz = useWizardStore();
    expect(controllerYaml(wiz.$state)).not.toContain('maintenance:');
    expect(controllerYaml(wiz.$state)).not.toContain('share:');
    wiz.maintenanceEnabled = true;
    wiz.shareEnabled = true;
    const out = controllerYaml(wiz.$state);
    expect(out).toContain('maintenance:');
    expect(out).toContain('share:');
  });
});

describe('daemonYaml', () => {
  it('emits identity + controller link + reconnect defaults', () => {
    const wiz = useWizardStore();
    wiz.nodeId = 'node-a';
    wiz.controllerHost = '192.168.1.10';
    wiz.joinToken = 'pcjt_test';
    const out = daemonYaml(wiz.$state);
    expect(out).toContain('nodeId: node-a');
    expect(out).toContain('host: 192.168.1.10');
    expect(out).toContain('joinToken: pcjt_test');
    expect(out).toContain('reconnect:');
    expect(out).toContain('  multiplier: 2');
  });

  it('omits the modules.signing block when not required', () => {
    const wiz = useWizardStore();
    wiz.daemonModulesSigningRequired = false;
    expect(daemonYaml(wiz.$state)).not.toMatch(/^modules:/m);
  });

  it('emits modules.signing.required: true when daemon signing is required', () => {
    const wiz = useWizardStore();
    wiz.daemonModulesSigningRequired = true;
    wiz.daemonModulesSigningMode = 'COSIGN_BUNDLE';
    const out = daemonYaml(wiz.$state);
    expect(out).toContain('modules:');
    expect(out).toContain('required: true');
    expect(out).toContain('mode: COSIGN_BUNDLE');
  });
});

describe('dashboardCompose', () => {
  it('substitutes the listen port + URLs into the compose service', () => {
    const wiz = useWizardStore();
    wiz.dashboardListenPort = 3000;
    wiz.dashboardControllerUrl = 'http://controller:8080';
    wiz.dashboardPublicUrl = 'https://dash.example.com';
    const out = dashboardCompose(wiz.$state);
    expect(out).toContain('- "3000:3000"');
    expect(out).toContain('CONTROLLER_URL: http://controller:8080');
    expect(out).toContain('PUBLIC_URL: https://dash.example.com');
  });
});

describe('dashboardNginx', () => {
  it('uses the controller origin in proxy_pass lines', () => {
    const wiz = useWizardStore();
    wiz.dashboardControllerUrl = 'https://controller.example.com:8443';
    const out = dashboardNginx(wiz.$state);
    expect(out).toContain('proxy_pass https://controller.example.com:8443;');
  });

  it('falls back to http://controller:8080 when the URL is malformed', () => {
    const wiz = useWizardStore();
    wiz.dashboardControllerUrl = 'not a url';
    const out = dashboardNginx(wiz.$state);
    expect(out).toContain('proxy_pass http://controller:8080;');
  });
});

describe('yamlFor', () => {
  it('dispatches to the right emitter per filename', () => {
    const wiz = useWizardStore();
    expect(yamlFor(wiz.$state, 'controller.yml').startsWith('# Generated')).toBe(true);
    expect(yamlFor(wiz.$state, 'daemon.yml')).toContain('nodeId:');
    expect(yamlFor(wiz.$state, 'docker-compose.yml')).toContain('services:');
    expect(yamlFor(wiz.$state, 'nginx.conf')).toContain('server {');
    expect(yamlFor(wiz.$state, 'unknown')).toBe('');
  });
});
