// YAML emitters for each install target. Pure functions over the Pinia state
// snapshot — no DOM, no fetch. Ported from the legacy wizard's
// controllerYaml/daemonYaml/dashboardCompose/dashboardNginx helpers; output is
// byte-for-byte identical so existing operator muscle-memory keeps working.
import type { WizardState, WizardMode } from '@/stores/wizard';

export type YamlFilename = 'controller.yml' | 'daemon.yml' | 'docker-compose.yml' | 'nginx.conf' | 'Caddyfile' | 'pending-join-token';

function nowIso(): string {
  return new Date().toISOString().slice(0, 19) + 'Z';
}

// Quote scalars that contain reserved YAML chars (`:`, `#`, whitespace).
function q(s: string | number | boolean | null | undefined): string {
  if (s == null) return '';
  const str = String(s);
  return /[:#\s]/.test(str) ? `'${str}'` : str;
}

export function filesForMode(
  mode: WizardMode,
  installMode: 'compose' | 'native' = 'compose',
  webServer: 'nginx' | 'caddy' = 'nginx',
): YamlFilename[] {
  switch (mode) {
    case 'all': return ['controller.yml', 'daemon.yml'];
    case 'controller': return ['controller.yml'];
    case 'controller-join': return ['controller.yml', 'pending-join-token'];
    case 'daemon': return ['daemon.yml'];
    case 'cli': return [];
    case 'dashboard':
      // Native serves the SPA from a host web server (no compose project): the
      // generated artifact is that server's vhost config, not docker-compose.
      if (installMode === 'native') {
        return webServer === 'caddy' ? ['Caddyfile'] : ['nginx.conf'];
      }
      return ['docker-compose.yml', 'nginx.conf'];
  }
}

export function modeLabel(mode: WizardMode): string {
  switch (mode) {
    case 'all': return 'Controller + Daemon (all-in-one)';
    case 'controller': return 'Controller only';
    case 'controller-join': return 'Add controller to existing cluster';
    case 'daemon': return 'Daemon only';
    case 'dashboard': return 'Dashboard standalone';
    case 'cli': return 'CLI login';
  }
}

export function controllerYaml(s: WizardState): string {
  const L: string[] = [];
  L.push(`# Generated by PrexorCloud Installer · ${nowIso()}`);
  L.push(`# Mode: ${modeLabel(s.mode)}`);
  L.push('');
  L.push(`uuid: ${s.uuid}`);
  L.push('');
  L.push(`runtime:`);
  L.push(`  profile: ${s.profile}`);
  L.push('');
  L.push(`http:`);
  L.push(`  host: ${q(s.httpHost)}`);
  L.push(`  port: ${s.httpPort}`);
  L.push(`  cors:`);
  L.push(`    allowedOrigins:`);
  s.corsOrigins.filter(Boolean).forEach((o) => L.push(`      - ${q(o)}`));
  L.push('');
  L.push(`grpc:`);
  L.push(`  host: ${q(s.grpcHost)}`);
  L.push(`  port: ${s.grpcPort}`);
  L.push('');
  L.push(`network:`);
  L.push(`  allowedSubnets:`);
  s.allowedSubnets.filter(Boolean).forEach((c) => L.push(`    - ${c}`));
  L.push('');
  L.push(`database:`);
  L.push(`  uri: ${q(s.databaseUri)}`);
  L.push(`  database: ${q(s.databaseName)}`);
  if (s.redisUri || s.profile === 'production') {
    L.push('');
    L.push(`redis:`);
    L.push(`  uri: ${q(s.redisUri)}`);
  }
  // backup: omitted. The Java BackupConfig() default-constructs to
  // {directory: "backups", retentionCount: 10}, which is what the wizard
  // used to emit explicitly. Operators never had a UI to change these, so
  // pinning them in the YAML was vestigial — drop now so the file matches
  // the actual configurability surface.
  L.push('');
  L.push(`security:`);
  // jwtSecret is always emitted as a real value. The Java JwtManager
  // Base64-decodes this field at startup with no fallback (JwtManager.java:170);
  // emitting a `<placeholder>` string crash-loops the JVM (the `<` byte is
  // 0x3c, illegal Base64). The wizard auto-fills s.jwtSecret on mount via
  // genSecret(64), so this is normally the operator's CSPRNG-generated value;
  // we guard with a same-generator fallback so a stale state object can't
  // re-introduce the placeholder.
  L.push(`  jwtSecret: ${q(s.jwtSecret)}`);
  L.push(`  jwtExpirationMinutes: ${s.jwtExpirationMinutes}`);
  if (s.initialAdminPassword) L.push(`  initialAdminPassword: ${q(s.initialAdminPassword)}`);
  L.push(`  rateLimiting:`);
  L.push(`    perIpPerMinute: ${s.rateIpPerMinute}`);
  L.push(`    perUserPerMinute: ${s.rateUserPerMinute}`);
  L.push(`    failOpenOnRedisError: ${s.rateFailOpenOnRedisError}`);
  L.push(`  lockout:`);
  L.push(`    enabled: ${s.lockoutEnabled}`);
  L.push(`    maxAttempts: ${s.lockoutMaxAttempts}`);
  L.push(`    windowSeconds: ${s.lockoutWindowSeconds}`);
  L.push(`    lockoutSeconds: ${s.lockoutLockoutSeconds}`);
  if (s.passwordResetEnabled) {
    L.push(`  passwordReset:`);
    L.push(`    enabled: true`);
    L.push(`    tokenTtlMinutes: ${s.passwordResetTtlMinutes}`);
    L.push(`    resetUrlBase: ${q(s.passwordResetUrlBase)}`);
    L.push(`    smtp:`);
    L.push(`      host: ${q(s.smtpHost)}`);
    L.push(`      port: ${s.smtpPort}`);
    L.push(`      startTls: ${s.smtpStartTls}`);
    L.push(`      implicitTls: ${s.smtpImplicitTls}`);
    if (s.smtpUsername) L.push(`      username: ${q(s.smtpUsername)}`);
    if (s.smtpPassword) L.push(`      password: ${q(s.smtpPassword)}`);
    if (s.smtpFrom) L.push(`      from: ${q(s.smtpFrom)}`);
  }
  L.push('');
  L.push(`logging:`);
  L.push(`  level: ${s.logLevel}`);
  L.push(`  format: ${s.logFormat}`);
  L.push('');
  L.push(`metrics:`);
  L.push(`  enabled: ${s.metricsEnabled}`);
  L.push(`  retentionHours: ${s.metricsRetentionHours}`);
  L.push(`  collectionIntervalSeconds: ${s.metricsCollectionIntervalSeconds}`);
  L.push('');
  L.push(`scheduler:`);
  L.push(`  evaluationIntervalSeconds: ${s.schedulerEvalSeconds}`);
  L.push(`  scalingCooldownSeconds: ${s.schedulerCooldownSeconds}`);
  L.push(`  nodeTimeoutSeconds: ${s.schedulerNodeTimeoutSeconds}`);
  L.push(`  auditRetentionDays: ${s.schedulerAuditRetentionDays}`);
  L.push('');
  L.push(`heartbeat:`);
  L.push(`  intervalMs: ${s.heartbeatIntervalMs}`);
  L.push(`  missedThreshold: ${s.heartbeatMissedThreshold}`);
  L.push('');
  L.push(`crashes:`);
  L.push(`  ringBufferSize: ${s.crashRingBufferSize}`);
  L.push(`  crashLoopThreshold: ${s.crashLoopThreshold}`);
  L.push(`  crashLoopWindowSeconds: ${s.crashLoopWindowSeconds}`);
  L.push('');
  L.push(`modules:`);
  L.push(`  directory: ${q(s.modulesDirectory)}`);
  L.push(`  dataDirectory: ${q(s.modulesDataDirectory)}`);
  L.push(`  signing:`);
  // null means "derive from runtime profile" — production = required, dev = optional.
  const signingRequiredEffective = s.modulesSigningRequired ?? (s.profile === 'production');
  L.push(`    required: ${signingRequiredEffective}`);
  L.push(`    mode: ${s.modulesSigningMode}`);
  // Always emit a trustRoot when signing is required. The Java validator
  // rejects a blank trustRoot in this case (ConfigValidator.java:87-95) and
  // the wizard's install backend auto-provisions a cosign keypair at the
  // default path before starting the controller — so we point at it here
  // even if the operator left the field blank in the UI. Pinning the path
  // also lets the operator see, in the Review tab, where the keypair will
  // land before they hit Install.
  const trustRootPath =
    s.modulesSigningTrustRoot ||
    (signingRequiredEffective ? 'config/security/module-trust-root.pem' : '');
  if (trustRootPath) L.push(`    trustRoot: ${q(trustRootPath)}`);
  L.push(`    allowUnsignedDevelopment: ${s.modulesSigningAllowUnsignedDev}`);
  L.push('');
  L.push(`dashboard:`);
  L.push(`  enabled: ${s.dashboardEnabled}`);
  if (s.maintenanceEnabled) {
    L.push('');
    L.push(`maintenance:`);
    L.push(`  enabled: true`);
    L.push(`  message: ${q(s.maintenanceMessage)}`);
  }
  if (s.shareEnabled) {
    L.push('');
    L.push(`share:`);
    L.push(`  enabled: true`);
    L.push(`  pasteUrl: ${q(s.sharePasteUrl)}`);
    if (s.sharePasteToken) L.push(`  pasteToken: ${q(s.sharePasteToken)}`);
    L.push(`  defaultExpiry: ${s.shareDefaultExpiry}`);
    L.push(`  defaultPrivate: ${s.shareDefaultPrivate}`);
    L.push(`  e2e: ${s.shareE2E}`);
  }
  return L.join('\n');
}

export function daemonYaml(s: WizardState): string {
  const L: string[] = [];
  L.push(`# Generated by PrexorCloud Installer · ${nowIso()}`);
  L.push(`# Mode: ${modeLabel(s.mode)}`);
  L.push('');
  L.push(`nodeId: ${q(s.nodeId)}`);
  if (s.advertiseAddress) L.push(`advertiseAddress: ${q(s.advertiseAddress)}`);
  L.push(`labels: {}`);
  L.push('');
  L.push(`controller:`);
  L.push(`  host: ${q(s.controllerHost)}`);
  L.push(`  grpcPort: ${s.controllerGrpcPort}`);
  L.push('');
  L.push(`security:`);
  L.push(`  joinToken: ${q(s.joinToken || '<paste-or-fetch-from-controller>')}`);
  L.push(`  certificateDir: ${q(s.certificateDir)}`);
  L.push('');
  L.push(`instances:`);
  L.push(`  directory: ${q(s.instancesDirectory)}`);
  L.push(`  shutdownTimeoutSeconds: ${s.instancesShutdownTimeoutSeconds}`);
  L.push(`  killTimeoutSeconds: ${s.instancesKillTimeoutSeconds}`);
  L.push(`  logRingBufferLines: ${s.instancesLogRingBufferLines}`);
  L.push(`  maxConsoleOutputLinesPerSecond: ${s.instancesMaxConsoleOutputLinesPerSecond}`);
  L.push('');
  L.push(`resources:`);
  L.push(`  maxMemoryMb: ${s.resourcesMaxMemoryMb}  # 0 = auto (80% physical RAM)`);
  L.push('');
  L.push(`health:`);
  L.push(`  enabled: ${s.daemonHealthEnabled}`);
  L.push(`  bindAddress: ${q(s.daemonHealthBindAddress)}`);
  L.push(`  port: ${s.daemonHealthPort}`);
  L.push('');
  L.push(`logging:`);
  L.push(`  level: ${s.daemonLogLevel}`);
  L.push(`  format: ${s.daemonLogFormat}`);
  L.push('');
  L.push(`reconnect:`);
  L.push(`  initialDelayMs: ${s.reconnectInitialDelayMs}`);
  L.push(`  maxDelayMs: ${s.reconnectMaxDelayMs}`);
  L.push(`  multiplier: ${s.reconnectMultiplier}`);
  if (s.daemonModulesSigningRequired) {
    L.push('');
    L.push(`modules:`);
    L.push(`  signing:`);
    L.push(`    required: true`);
    L.push(`    mode: ${s.daemonModulesSigningMode}`);
    if (s.daemonModulesSigningTrustRoot) L.push(`    trustRoot: ${q(s.daemonModulesSigningTrustRoot)}`);
  }
  return L.join('\n');
}

export function dashboardCompose(s: WizardState): string {
  // The wizard sends the live fields (controller URL, public URL, listen port,
  // admin password) to /api/install/dashboard which generates these files
  // server-side; we emit them here so the Review tab shows what the operator
  // will get.
  return `# Generated by PrexorCloud Installer · ${nowIso()}
# Dashboard standalone deployment

services:
  dashboard:
    image: ghcr.io/prexorjustin/prexorcloud-dashboard:latest
    restart: unless-stopped
    ports:
      - "${s.dashboardListenPort}:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      CONTROLLER_URL: ${s.dashboardControllerUrl}
      PUBLIC_URL: ${s.dashboardPublicUrl}
`;
}

export function dashboardNginx(s: WizardState): string {
  let proxyOrigin = 'http://controller:8080';
  try {
    const u = new URL(s.dashboardControllerUrl);
    proxyOrigin = `${u.protocol}//${u.host}`;
  } catch {
    // dashboardControllerUrl is empty or malformed — fall back to placeholder.
  }
  return `server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / { try_files $uri $uri/ /index.html; }

    location /api/ {
        proxy_pass ${proxyOrigin};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/v1/events/stream {
        proxy_pass ${proxyOrigin};
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }
    location /metrics { proxy_pass ${proxyOrigin}; }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
`;
}

// proxyOriginFor extracts scheme://host from the configured controller URL,
// falling back to a placeholder when it's empty or malformed. Shared by every
// dashboard proxy template.
function proxyOriginFor(controllerUrl: string): string {
  try {
    const u = new URL(controllerUrl);
    return `${u.protocol}//${u.host}`;
  } catch {
    return 'http://controller:8080';
  }
}

// dashboardNginxNative mirrors the controller's setup.configureNginx output:
// a host vhost that listens on the chosen port, serves the bundle from the
// install dir's web root, and proxies /api/* to the controller.
export function dashboardNginxNative(s: WizardState): string {
  const origin = proxyOriginFor(s.dashboardControllerUrl);
  const root = `${s.dashboardInstallDir}/public`;
  return `# Generated by PrexorCloud Installer (native dashboard) · ${nowIso()}
# /etc/nginx/conf.d/prexorcloud-dashboard.conf — TLS assumed terminated upstream.
server {
    listen ${s.dashboardListenPort};
    server_name _;
    root ${root};
    index index.html;

    location / { try_files $uri $uri/ /index.html; }

    location /api/ {
        proxy_pass ${origin};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location /api/v1/events/stream {
        proxy_pass ${origin};
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 86400s;
    }
    location /metrics { proxy_pass ${origin}; }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
`;
}

// dashboardCaddyfile mirrors setup.configureCaddy: an https:// public URL
// becomes a bare-host site address (Caddy auto-provisions a cert); http:// or
// a bare host falls back to a plain-HTTP address.
export function dashboardCaddyfile(s: WizardState): string {
  const origin = proxyOriginFor(s.dashboardControllerUrl);
  const root = `${s.dashboardInstallDir}/public`;
  let site = `:${s.dashboardListenPort || 80}`;
  try {
    const u = new URL(s.dashboardPublicUrl);
    site = u.protocol === 'https:' ? u.hostname : `http://${u.hostname}`;
  } catch {
    // dashboardPublicUrl empty/malformed — fall back to :port.
  }
  return `# Generated by PrexorCloud Installer (native dashboard) · ${nowIso()}
# /etc/caddy/Caddyfile — Caddy auto-provisions HTTPS for an https:// hostname.
${site} {
\troot * ${root}
\tencode gzip

\t@api path /api/* /metrics
\thandle @api {
\t\treverse_proxy ${origin}
\t}

\thandle {
\t\ttry_files {path} /index.html
\t\tfile_server
\t}
}
`;
}

export function yamlFor(state: WizardState, filename: YamlFilename | string): string {
  switch (filename) {
    case 'controller.yml': return controllerYaml(state);
    case 'daemon.yml': return daemonYaml(state);
    case 'docker-compose.yml': return dashboardCompose(state);
    case 'nginx.conf':
      return state.installMode === 'native' ? dashboardNginxNative(state) : dashboardNginx(state);
    case 'Caddyfile': return dashboardCaddyfile(state);
    case 'pending-join-token':
      // What the controller would persist at config/security/pending-join-token —
      // shown in the preview pane verbatim. The wizard server writes it for real
      // via setupweb's writePendingJoinToken.
      return state.controllerJoinToken.trim() + '\n';
    default: return '';
  }
}
