package me.prexorjustin.prexorcloud.controller.template;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Ensures base templates exist. The root {@code base} template is created on
 * startup; platform-specific {@code base-{platform}} templates are created
 * lazily when a group first references a platform.
 *
 * <p>
 * Platform default config files are loaded from classpath resources at
 * {@code platform-defaults/} rather than hardcoded in Java. This makes them
 * easy to read, diff, and override without recompilation.
 */
public final class BaseTemplateGenerator {

    private static final Logger logger = LoggerFactory.getLogger(BaseTemplateGenerator.class);

    private static final String DEFAULTS_ROOT = "defaults/platform";

    private final TemplateManager templateManager;

    public BaseTemplateGenerator(TemplateManager templateManager) {
        this.templateManager = templateManager;
    }

    private static final Map<String, String> BUNDLED_PLUGINS = Map.of(
            "paper",
            "PrexorCloudPaperPlugin.jar",
            "spigot",
            "PrexorCloudSpigotPlugin.jar",
            "velocity",
            "PrexorCloudVelocityPlugin.jar",
            "bungeecord",
            "PrexorCloudBungeecordPlugin.jar",
            "geyser",
            "PrexorCloudGeyserExtension.jar");

    // Where each format's bundled jar is installed inside the instance. Geyser loads its integration
    // as an Extension from extensions/; the Bukkit/proxy families load from plugins/ (the default).
    private static final Map<String, String> BUNDLED_PLUGIN_DIRS = Map.of("geyser", "extensions");

    /**
     * Ensure the root base template exists. Called on startup.
     */
    public void ensureBaseTemplates() throws IOException {
        ensureTemplate("base", "Root base template", "");
    }

    /**
     * Ensure the {@code base-{platform}} template exists, creating it with default
     * config files and bundled plugins when missing. Safe to call multiple times --
     * skips if the template already exists.
     *
     * @param platform
     *            the platform name (e.g. "paper", "purpur", "velocity")
     * @param category
     *            SERVER or PROXY
     * @param configFormat
     *            the config template set to use (paper, spigot, velocity,
     *            bungeecord). Forks share their parent's format (e.g. purpur →
     *            paper, waterfall → bungeecord).
     */
    public void ensurePlatformTemplate(String platform, String category, String configFormat) throws IOException {
        String lowerPlatform = platform.toLowerCase();
        String templateName = "base-" + lowerPlatform;

        if (templateManager.exists(templateName)) return;

        // Resolve config format: explicit format takes priority, fall back to platform
        // name
        String format = (configFormat != null && !configFormat.isBlank()) ? configFormat.toLowerCase() : lowerPlatform;

        // Suppress watcher during setup -- we'll rehash once at the end
        templateManager.suppressWatcher(templateName);
        try {
            ensureTemplate(templateName, "Base " + platform + " template", lowerPlatform);

            if ("PROXY".equalsIgnoreCase(category)) {
                // Proxy configs (velocity.toml, bungeecord/config.yml) are fully
                // defined in resource defaults — the proxy reads them as-is.
                copyResourceTree(format, templateName);
            } else {
                // Game server defaults: server.properties (with variable placeholders)
                // and eula.txt. Paper/Spigot-specific configs (paper-global.yml, spigot.yml)
                // are NOT shipped as templates — they are generated by the bootstrap cache
                // on the daemon and patched by ServerConfigPatcher. This avoids shipping
                // minimal stubs that Paper/Spigot would overwrite with defaults on first boot.
                copyResourceTree("server", templateName);
            }

            // Velocity modern forwarding requires a shared secret on both proxy
            // and game server sides. The same secret file is placed in both templates.
            if ("velocity".equals(format) || "paper".equals(format)) {
                createForwardingSecret(templateName);
            }

            String pluginJar = BUNDLED_PLUGINS.get(format);
            if (pluginJar != null) {
                installBundledPlugin(templateName, pluginJar, BUNDLED_PLUGIN_DIRS.getOrDefault(format, "plugins"));
            }

            // Save once with final hash — no rehash event
            templateManager.get(templateName).ifPresent(cfg -> {
                try {
                    templateManager.save(cfg);
                } catch (IOException e) {
                    logger.warn("Failed to save final hash for template {}: {}", templateName, e.getMessage());
                }
            });
        } finally {
            templateManager.unsuppressWatcher(templateName);
        }
    }

    private void ensureTemplate(String name, String description, String platform) throws IOException {
        if (templateManager.exists(name)) return;

        var config = new TemplateConfig(name, description, platform, "", 0);
        templateManager.save(config);
        logger.debug("Created base template: {}", name);
    }

    /**
     * Copies all resource files matching the given prefix from the
     * {@code platform-defaults/} classpath directory into the template's files dir.
     * Uses {@code manifest.txt} to enumerate available resources (since classpath
     * directories cannot be listed reliably from inside JARs).
     *
     * @param prefix
     *            the resource prefix to match (e.g. "server", "paper")
     * @param templateName
     *            the target template to copy files into
     */
    private void copyResourceTree(String prefix, String templateName) throws IOException {
        List<String> manifest = readManifest();
        Path filesDir = templateManager.getTemplateFilesDir(templateName);
        String prefixWithSlash = prefix + "/";

        for (String entry : manifest) {
            if (!entry.startsWith(prefixWithSlash)) continue;

            // Relative path within the template (strip the prefix)
            String relativePath = entry.substring(prefixWithSlash.length());
            Path target = filesDir.resolve(relativePath);
            if (Files.exists(target)) continue;

            try (InputStream in = getClass().getClassLoader().getResourceAsStream(DEFAULTS_ROOT + "/" + entry)) {
                if (in == null) {
                    logger.warn("Platform default resource not found: {} -- skipping", entry);
                    continue;
                }
                Files.createDirectories(target.getParent());
                Files.copy(in, target);
            }
        }
    }

    private List<String> readManifest() throws IOException {
        try (InputStream in = getClass().getClassLoader().getResourceAsStream(DEFAULTS_ROOT + "/manifest.txt")) {
            if (in == null) {
                throw new IOException("Platform defaults manifest not found on classpath");
            }
            try (var reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
                return reader.lines()
                        .map(String::trim)
                        .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                        .toList();
            }
        }
    }

    /**
     * Creates a shared forwarding secret file. Both Velocity and Paper templates
     * use this to authenticate the modern forwarding handshake. The secret is
     * generated once at controller startup and stored in {@code config/security/}.
     */
    private void createForwardingSecret(String templateName) throws IOException {
        Path filesDir = templateManager.getTemplateFilesDir(templateName);
        Files.createDirectories(filesDir);

        Path secretFile = filesDir.resolve("forwarding.secret");
        if (Files.exists(secretFile)) return;

        String secret = templateManager.getForwardingSecret();
        Files.writeString(secretFile, secret);
    }

    /**
     * Copies a bundled plugin JAR from the controller's classpath into the
     * template's {@code installDir} (usually {@code plugins}; {@code extensions}
     * for Geyser). Skips if the file already exists -- this avoids overwriting a
     * newer plugin version that was deployed manually.
     */
    private void installBundledPlugin(String templateName, String jarName, String installDir) throws IOException {
        Path pluginsDir = templateManager.getTemplateFilesDir(templateName).resolve(installDir);
        Files.createDirectories(pluginsDir);

        Path target = pluginsDir.resolve(jarName);
        if (Files.exists(target)) return;

        try (InputStream in = getClass().getResourceAsStream("/bundled-plugins/" + jarName)) {
            if (in == null) {
                logger.warn("Bundled plugin {} not found on classpath -- skipping", jarName);
                return;
            }
            Files.copy(in, target);
            logger.debug("Installed bundled plugin {} into template {}", jarName, templateName);
        }
    }
}
