// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import vue from '@astrojs/vue';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import tailwind from '@astrojs/tailwind';
import starlightOpenAPI, { openAPISidebarGroups } from 'starlight-openapi';
import remarkMermaid from './src/lib/remark-mermaid.mjs';

// Reference / concepts / internals get rendered with `collapsed: true`
// so the sidebar isn't intimidating on first load — readers expand the
// section they actually need.

// https://astro.build/config
export default defineConfig({
  site: 'https://prexor.cloud',
  integrations: [
    vue(),
    // Starlight registers astro-expressive-code internally and must come
    // before @astrojs/mdx so MDX-rendered code blocks pick up the
    // expressive-code transformer.
    starlight({
      title: 'PrexorCloud',
      description:
        'Self-hosted, OSS Minecraft cloud orchestrator. Deploy, scale, and manage Minecraft server infrastructure with zero-trust security and intelligent scheduling.',
      // starlight-openapi walks docs/openapi.json (auto-generated by the
      // controller's javalin-openapi-plugin annotation processor) at build
      // time and emits one Starlight page per operation under
      // `/reference/rest-api/...`, grouped by tag. Pagefind-indexed,
      // sidebar-integrated, single source of truth.
      plugins: [
        starlightOpenAPI([
          {
            base: 'reference/rest-api',
            label: 'REST API',
            schema: '../docs/openapi.json',
            collapsed: true,
          },
        ]),
      ],
      logo: {
        light: './src/assets/logo.svg',
        dark: './src/assets/logo-dark.svg',
        replacesTitle: false,
      },
      favicon: '/favicon.svg',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/prexorjustin/prexorcloud',
        },
      ],
      editLink: {
        baseUrl:
          'https://github.com/prexorjustin/prexorcloud/edit/main/docs/public/en/',
      },
      // We ship our own 404 at `src/pages/404.astro` (design-system glass card
      // with recovery links) — disable Starlight's default to avoid the
      // route-collision warning that becomes a hard error in future Astro.
      disable404Route: true,
      // Override Starlight's <Head> so our client-side mermaid bootstrap
      // (src/scripts/mermaid.ts) gets bundled and loaded on every docs page.
      // The bootstrap dynamically imports `mermaid` only when a diagram is
      // present, so non-diagram pages pay zero extra JS.
      components: {
        Head: './src/components/docs/Head.astro',
        Footer: './src/components/docs/Footer.astro',
        // Replaces Starlight's stock <select> dropdown with a 3-position
        // pill slider (Light · Auto · Dark) — see
        // src/components/docs/ThemeSelect.astro. Keeps Starlight's
        // localStorage contract (`starlight-theme` key) so the existing
        // server-side default + media-query handler keep working.
        ThemeSelect: './src/components/docs/ThemeSelect.astro',
      },
      sidebar: [
        {
          label: 'Getting Started',
          items: [
            { label: 'What is PrexorCloud?', link: '/getting-started/what-is-prexorcloud/' },
            { label: 'Installation',         link: '/getting-started/installation/' },
            { label: 'Quickstart (10 min)',  link: '/getting-started/quickstart/' },
            { label: 'Core Concepts',        link: '/getting-started/core-concepts/' },
            { label: 'Your First Network',   link: '/getting-started/your-first-network/' },
          ],
        },
        {
          label: 'Concepts',
          items: [
            { label: 'Architecture',                link: '/concepts/architecture/' },
            { label: 'Cluster Model',               link: '/concepts/cluster-model/' },
            { label: 'Groups, Instances, Templates', link: '/concepts/groups-instances-templates/' },
            { label: 'Scheduling + Auto-Scaling',   link: '/concepts/scheduling-and-scaling/' },
            {
              label: 'Module System',
              collapsed: true,
              items: [
                { label: 'Overview',                link: '/concepts/modules/' },
                { label: 'Platform Modules',        link: '/concepts/modules/platform/' },
                { label: 'Daemon Modules',          link: '/concepts/modules/daemon/' },
                { label: 'Capability Registry',    link: '/concepts/modules/capabilities/' },
                { label: 'Module Lifecycle',        link: '/concepts/modules/lifecycle/' },
              ],
            },
            { label: 'Plugin System',                link: '/concepts/plugins/' },
            { label: 'Events + EventBus',            link: '/concepts/events/' },
            { label: 'Security',                     link: '/concepts/security/' },
            { label: 'Deployments + Rolling Updates', link: '/concepts/deployments/' },
          ],
        },
        {
          label: 'Guides',
          collapsed: true,
          items: [
            { label: 'Multi-Node Setup',     link: '/guides/multi-node-setup/' },
            { label: 'Rolling Deployments',  link: '/guides/rolling-deployments/' },
            { label: 'Crash Recovery',       link: '/guides/crash-recovery/' },
            { label: 'Custom Scaling Rules', link: '/guides/custom-scaling-rules/' },
            { label: 'Backup + Restore',     link: '/guides/backup-and-restore/' },
            { label: 'HA Controller (Redis)', link: '/guides/ha-controller/' },
          ],
        },
        {
          label: 'Operations',
          collapsed: true,
          items: [
            { label: 'Production Checklist',     link: '/operations/production-checklist/' },
            { label: 'Configuration Reference', link: '/operations/configuration/' },
            { label: 'Monitoring + Metrics',    link: '/operations/monitoring/' },
            { label: 'Logs + Audit',             link: '/operations/logs-and-audit/' },
            { label: 'Backups + DR',             link: '/operations/backups-and-dr/' },
            { label: 'Upgrading',                link: '/operations/upgrading/' },
            { label: 'HA Setup',                 link: '/operations/ha-setup/' },
            { label: 'Disaster Drill',           link: '/operations/disaster-drill/' },
          ],
        },
        {
          label: 'Recipes',
          collapsed: true,
          items: [
            { label: 'BedWars Network',           link: '/recipes/bedwars-network/' },
            { label: 'Survival Server',           link: '/recipes/survival-server/' },
            { label: 'Multi-Game Network',        link: '/recipes/multi-game-network/' },
            { label: 'Reverse Proxy in Front',    link: '/recipes/reverse-proxy/' },
            { label: 'CI/CD Deployments',         link: '/recipes/cicd-deployments/' },
            { label: 'Discord Notifications',     link: '/recipes/discord-notifications/' },
            { label: 'Custom Scaling Logic',      link: '/recipes/custom-scaling-logic/' },
            { label: 'Migrate from CloudNet 4',   link: '/recipes/migrate-from-cloudnet/' },
            { label: 'Migrate from SimpleCloud V2', link: '/recipes/migrate-from-simplecloud/' },
            { label: 'Migrate from Pterodactyl',  link: '/recipes/migrate-from-pterodactyl/' },
          ],
        },
        {
          label: 'Reference',
          items: [
            // Phase 5: starlight-openapi emits the REST sidebar group at build
            // time from docs/openapi.json — see `openAPISidebarGroups` spread
            // below. This keeps the rest of the Reference IA hand-curated.
            ...openAPISidebarGroups,
            { label: 'API Playground', link: '/playground/' },
            {
              label: 'CLI (prexorctl)',
              collapsed: true,
              items: [
                { label: 'Overview',              link: '/reference/cli/' },
                { label: 'Setup + Auth',          link: '/reference/cli/setup-and-auth/' },
                { label: 'Cluster Commands',     link: '/reference/cli/cluster/' },
                { label: 'Group + Instance',     link: '/reference/cli/group-and-instance/' },
                { label: 'Templates',             link: '/reference/cli/templates/' },
                { label: 'Users + Roles',         link: '/reference/cli/users-and-roles/' },
                { label: 'Modules + Plugins',     link: '/reference/cli/modules-and-plugins/' },
                { label: 'Utilities + Scripting', link: '/reference/cli/utilities/' },
              ],
            },
            {
              label: 'Module SDK',
              collapsed: true,
              items: [
                { label: 'Overview',                link: '/reference/module-sdk/' },
                { label: 'PlatformModule',          link: '/reference/module-sdk/platform-module/' },
                { label: 'DaemonModule',            link: '/reference/module-sdk/daemon-module/' },
                { label: 'ModuleContext',           link: '/reference/module-sdk/module-context/' },
                { label: 'EventBus',                link: '/reference/module-sdk/event-bus/' },
                { label: 'Capability API',          link: '/reference/module-sdk/capability-api/' },
                { label: 'Storage API',             link: '/reference/module-sdk/storage-api/' },
                { label: 'REST Routes',             link: '/reference/module-sdk/rest-routes/' },
                { label: 'module.yaml Manifest',    link: '/reference/module-sdk/module-yaml/' },
              ],
            },
            {
              label: 'Plugin SDK',
              collapsed: true,
              items: [
                { label: 'Overview',           link: '/reference/plugin-sdk/' },
                { label: 'CloudPluginContext', link: '/reference/plugin-sdk/plugin-context/' },
                { label: 'EventHandler',       link: '/reference/plugin-sdk/event-handler/' },
                { label: 'Players + Commands', link: '/reference/plugin-sdk/players-and-commands/' },
                { label: '@CloudPlugin',       link: '/reference/plugin-sdk/cloudplugin-annotation/' },
              ],
            },
          ],
        },
        {
          label: 'Internals',
          collapsed: true,
          items: [
            { label: 'Architecture Deep-Dive', link: '/internals/architecture/' },
            {
              label: 'gRPC Protocol',
              collapsed: true,
              items: [
                { label: 'Overview',         link: '/internals/protocol/' },
                { label: 'DaemonService',    link: '/internals/protocol/daemon-service/' },
                { label: 'BootstrapService', link: '/internals/protocol/bootstrap-service/' },
                { label: 'AdminService',     link: '/internals/protocol/admin-service/' },
              ],
            },
            { label: 'Storage Schema',  link: '/internals/storage-schema/' },
            { label: 'Cosign Pipeline', link: '/internals/cosign-pipeline/' },
            { label: 'Tech Stack',      link: '/internals/tech-stack/' },
          ],
        },
        {
          label: 'Compare',
          collapsed: true,
          items: [
            { label: 'vs CloudNet 4',     link: '/compare/cloudnet-4/' },
            { label: 'vs SimpleCloud V2', link: '/compare/simplecloud-v2/' },
          ],
        },
        {
          label: 'Project',
          collapsed: true,
          items: [
            { label: 'Blog',                    link: '/blog/' },
            { label: 'Changelog',               link: '/changelog/' },
            { label: 'Performance Benchmarks',  link: '/benchmarks/' },
            { label: 'Contributing',            link: '/contributing/' },
          ],
        },
      ],
      customCss: [
        // 1. Tokens — single source of truth (cyan-9 accent, glass surfaces,
        //    Inter/Inter Tight/JetBrains Mono, slate-1 background).
        // 2. Starlight bridge — maps tokens onto Starlight's `--sl-color-*`
        //    properties + design-system utility classes (.glass-card,
        //    .text-gradient-title, .eyebrow, .bg-dot-pattern).
        // 3. Docs theme — the docs-only surface: typography, sidebar (cyan
        //    bar + uppercase eyebrows), callouts, code, tables, mermaid.
        //    Lives only here, not on landing/playground/404.
        './src/styles/tokens.css',
        './src/styles/starlight.css',
        // Generated from design-system/dist — maps --sl-color-* onto DS tokens.
        // Loaded after starlight.css so the generated mapping is authoritative.
        './src/styles/starlight-theme.generated.css',
        './src/styles/docs-theme.css',
      ],
      head: [
        {
          // Design-system theme color — slate-1 (#0a0a12), the canonical
          // dark background. Browser chrome on iOS Safari and Android picks
          // this up as the address-bar tint.
          tag: 'meta',
          attrs: { name: 'theme-color', content: '#0a0a12' },
        },
        // RSS auto-discovery — readers and most browsers expose this as
        // "subscribe" when present in <head>. Pointed at the engineering
        // blog feed emitted by src/pages/blog/rss.xml.ts.
        {
          tag: 'link',
          attrs: {
            rel: 'alternate',
            type: 'application/rss+xml',
            title: 'PrexorCloud Blog',
            href: '/blog/rss.xml',
          },
        },
        {
          tag: 'link',
          attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'preconnect',
            href: 'https://fonts.gstatic.com',
            crossorigin: '',
          },
        },
        {
          tag: 'link',
          attrs: {
            rel: 'stylesheet',
            // Three families per the design system (SKILL.md §Type rules):
            // Inter for UI, Inter Tight for display, JetBrains Mono for
            // code/terminal/tabular numerics. Nothing else.
            href: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Inter+Tight:wght@500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap',
          },
        },
      ],
    }),
    mdx(),
    tailwind({ applyBaseStyles: false }),
    sitemap(),
  ],
  vite: {
    // Force Vite to pre-bundle `mermaid` on dev-server startup. Without this
    // the runtime `import('mermaid')` in src/scripts/mermaid.ts triggers the
    // optimizer mid-request and the resulting chunk is occasionally served
    // with an empty Content-Type — Firefox + Safari then block it as a
    // disallowed MIME type and the diagrams stay un-rendered. Pre-bundling
    // sidesteps the race.
    optimizeDeps: {
      include: ['mermaid'],
    },
  },
  markdown: {
    shikiConfig: {
      theme: 'github-dark-default',
      // `langs: []` (default) loads Shiki's full bundled language set, which
      // covers java/kotlin/go/protobuf/powershell/toml/nginx/ini/properties
      // plus the obvious Web languages. Listing them explicitly hits a Shiki
      // type quirk (LanguageRegistration vs string) without runtime benefit.
      wrap: true,
    },
    // remark-mermaid runs *before* Shiki's expressive-code transformer so
    // ```mermaid fences are converted to <div class="mermaid"> HTML nodes
    // and never reach the syntax highlighter. The client-side bootstrap in
    // src/scripts/mermaid.ts then renders them on hydration.
    remarkPlugins: [remarkMermaid],
  },
});
